MSP432E4 DriverLib API Guide: cpu.h File Reference
cpu.h File Reference
#include <stdint.h>
Functions
uint32_t CPUcpsid (void)
uint32_t CPUcpsie (void)
uint32_t CPUprimask (void)
void CPUwfi (void)
uint32_t CPUbasepriGet (void)
void CPUbasepriSet (uint32_t ui32NewBasepri)
Function Documentation
CPUcpsid()
uint32_t CPUcpsid (void)
Referenced by IntMasterDisable().
CPUcpsie()
uint32_t CPUcpsie (void)
CPUprimask()
uint32_t CPUprimask (void)
CPUwfi()
void CPUwfi (void)
Referenced by SysCtlDeepSleep(), and SysCtlSleep().
CPUbasepriGet()
uint32_t CPUbasepriGet (void)
Referenced by IntPriorityMaskGet().
CPUbasepriSet()
void CPUbasepriSet (uint32_t ui32NewBasepri)
Referenced by IntPriorityMaskSet().
© Copyright 1995-2019, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale