USBLibAPIGuide: Dualmode_api
Dualmode_api
Functions
void USBDualModeInit (uint32_t ui32Index)
void USBDualModeTerm (uint32_t ui32Index)
Detailed Description
Function Documentation
USBDualModeInit()
void USBDualModeInit (uint32_t ui32Index)
Initializes the USB controller for dual mode operation.
Parameters
ui32Index specifies the USB controller that is to be initialized for dual mode operation. This parameter must be set to 0.
This function initializes the USB controller hardware into a state suitable for dual mode operation. Applications may use this function to ensure that the controller is in a neutral state and able to receive appropriate interrupts before host or device mode is chosen using a call to USBStackModeSet().
Returns
None.
References g_psDCDInst, InternalUSBTickInit(), USBHCDPowerAutomatic(), and USBHCDPowerConfigGet().
USBDualModeTerm()
void USBDualModeTerm (uint32_t ui32Index)
Returns the USB controller to the default mode when in dual mode operation.
Parameters
ui32Index specifies the USB controller whose dual mode operation is to be ended. This parameter must be set to 0.
Applications using both host and device modes may call this function to disable interrupts in preparation for shutdown or a change of operating mode.
Returns
None.
References g_psDCDInst.
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale